### PR TITLE
adding in photo information

### PR DESCRIPTION
**Pull request by alexjyong**

### CODE REVIEW

**Comment by capouch** [comment]
I am going to hold off on this until our next meeting SO THAT you can
explain how this process works to Will, in real time, and I will go through
the steps of doing it live.

That make sense?  This is how we ought to be doing this, but it will be
good to cover it.  I had intended to do that, but didn't recognize this as
the perfect opportunity.

b.

**Comment by alexjyong** [comment]
Sure thing

**Comment by capouch** [comment]
Wild.

Will just emailed to say that it really helped him to put together that
little presentation, and he thinks it ought to be a regular feature.

I agree, and so I told him your presentation on that will on our agenda for
Friday.

b.

**Comment by alexjyong** [comment]
I look forward to it!

**Pull request merged**
